### ISSUE TITLE
Shortcuts not working! 

### ISSUE THREAD

**Issue by Pupo1** [alonswartz/notesium#28] opened 2024-01-03 14:29 UTC
In my notesium Web instance, the editor shortcuts are not working. 
For example, when I type '[[' , nothing will happen. I guess, normally some kind of link dialog should appear?!?
I tried on firefox 121.0 under Debian 11.

**Comment by alonswartz** [comment] 2024-01-03 14:36
Yep, a dialog should appear. Could you check the browser developer tools console for any errors?
Do the regular list/links/search icons or keybindings bring up their dialogs?

**Comment by Pupo1** [comment] 2024-01-03 14:59
The only thing the developer tools console says, is : 
`Storage access automatically granted for origin “https://nichts/” on “http://localhost:41489/”.`

Regular icons like "conceal formatting", "links" function and bring up their dialogs.
I have no clue what you mean with "insert/edit mode", because I am on the web instance, not on vim. But I can type regular text like for example 'bla bla bla [[' and it will just show up as I typed it, without bringing up the dialog.

**Comment by alonswartz** [comment] 2024-01-03 15:22
Very strange...

Could you try with a pre-compiled binary to rule out any build issue? Alternatively, I'm attaching the vendor files which were included in the 0.5.1 release build:

```
build/0.5.1$ ./notesium-linux-amd64 extract web/app/vendor.css > vendor.css.txt
build/0.5.1$ ./notesium-linux-amd64 extract web/app/vendor.js > vendor.js.txt

build/0.5.1$ sha256sum vendor.*
ed9f028213320674647557c3bbed30dea6cb7703a749aa3d25572dedd2e7bd7c  vendor.css.txt
a39b1df0beef064b676eb25d2070496cea3bdd2f7f334b56392472d0fa2e5ab9  vendor.js.txt
```

Note: I saved them with the `.txt` suffix, as github doesn't support `css/js` attachments in issues. Please rename to remove the `.txt` and drop them in `notesium/web/app/`. Then either build, or specify the webroot:

```
notesium web --webroot=path/to/notesium/web
```
[vendor.js.txt](https://github.com/alonswartz/notesium/files/13820666/vendor.js.txt)
[vendor.css.txt](https://github.com/alonswartz/notesium/files/13820667/vendor.css.txt)

**Comment by Pupo1** [comment] 2024-01-03 15:36
I have replaced both vendor.js and vendor.css in the directory notesium/web/app and restarted the web server with ` notesium web --writable --webroot=/home/pupo1/notesium/web/  ` but nothing changes, the behaviour is still that there will no dialog pop up

**Comment by Pupo1** [comment] 2024-01-03 15:51
Esc works, yes. Ctrl-s works fine, too. I think it is a problem that, if the [[ fails to work, there is no other way to insert a link manually, because I don't know the file names by heart.

**Comment by Pupo1** [comment] 2024-01-03 15:53
I don't find any "intercepted" in the developer console under "filter output".

**Comment by Pupo1** [comment] 2024-01-03 16:08
The pre-compiled binary doesn't work also! I don't understand how that is possible.

**Comment by Pupo1** [comment] 2024-01-03 16:14
WHOA it works with the above edits!!! Thank you, I think I will just change it to "j" instead of "1". Happy that it works now. 

But if you want me to do other tests, just tell me what I should try next.

**Comment by alonswartz** [comment] 2024-01-03 16:14
Something else to try is to use single quotes around the `[` (don't forget to revert the `11` experiment...).

```diff
web/app$ gd note.js
diff --git a/web/app/note.js b/web/app/note.js
index 57caa8e..46cce5a 100644
--- a/web/app/note.js
+++ b/web/app/note.js
@@ -81,7 +81,7 @@ export default {
         highlightFormatting: true,
       },
       extraKeys: {
-        "[": this.handleLeftBracket,
+        '[': this.handleLeftBracket,
         "Esc": function(cm){ cm.display.input.blur(); document.body.focus(); },
         "Ctrl-S": this.handleSave,
       },
```

Does the binary segfault? I'm on a x86_64...
```
$ uname -mo
x86_64 GNU/Linux
```

**Comment by Pupo1** [comment] 2024-01-03 16:22
No the single quotes won't help unfortunately. 
$ uname 
x86_64 GNU/Linux

I am not sure if I understand the question. The precompiled binary works, but the [[ doesn't .

**Comment by alonswartz** [comment] 2024-01-03 16:26
Pity about the single quotes, I'll look into this and let you know... I'll leave the issue open for now.
Glad you have a workaround in the meantime, let me know if you come across any other issues or feedback. 

As for the binary, I misunderstood - I thought you meant the binary doesn't work at all ;)

**Comment by Pupo1** [comment] 2024-01-03 16:29
I have to admit that I find "jj" better that "[[" anyway - thanks for giving me that workaround! Let me know when I should test anything else.

**Comment by alonswartz** [comment] 2024-01-03 16:37
Good to know. In the future the keybindings will be configurable so that way you won't need to patch the source.

I'm currently working on a new release (labels and notes-list side panels), I'll probably push the branch in a day or 2 if you want to test it...

**Comment by Pupo1** [comment] 2024-01-03 16:39
(I don't know it if is of any interest or help for finding the reason of the issue, but when i change '1' to 'j' , it does not work, either. "jj" will just write "jj" and not open any dialog.)

**Comment by alonswartz** [comment] 2024-01-03 17:29
I can confirm that specifying lowercase `j` in the `extraKeys` doesn't work, but specifying capital `J` does. It is still triggered by typing lowercase `jj`. 

```diff

web/app$ gd note.js
diff --git a/web/app/note.js b/web/app/note.js
index 57caa8e..fd39e33 100644
--- a/web/app/note.js
+++ b/web/app/note.js
@@ -38,10 +38,10 @@ export default {
       const cursorPos = this.cm.getCursor();
       const startPos = { line: cursorPos.line, ch: cursorPos.ch - 1 };
       const prevChar = this.cm.getRange(startPos, cursorPos);
-      if (prevChar === '[') {
+      if (prevChar === 'j') {
         this.showFinder = true;
       } else {
-        this.cm.replaceRange('[', cursorPos, cursorPos);
+        this.cm.replaceRange('j', cursorPos, cursorPos);
       }
     },
     handleFinderSelection(value) {
@@ -81,7 +81,7 @@ export default {
         highlightFormatting: true,
       },
       extraKeys: {
-        "[": this.handleLeftBracket,
+        "J": this.handleLeftBracket,
         "Esc": function(cm){ cm.display.input.blur(); document.body.focus(); },
         "Ctrl-S": this.handleSave,
       },
```

**Comment by alonswartz** [comment] 2024-01-03 17:37
Both of these also work on my side - would be good if you could test as well. Thanks!

```diff
       extraKeys: {
-        "[": this.handleLeftBracket,
+        '\[': this.handleLeftBracket,
```
```diff
       extraKeys: {
-        "[": this.handleLeftBracket,
+        "\[": this.handleLeftBracket,
```

**Comment by alonswartz** [comment] 2024-01-04 15:34
It just dawned on me that you're using the `de_DE.utf8` locale, so is it safe to presume this implies a [german keyboard layout](https://en.wikipedia.org/wiki/German_keyboard_layout)? Meaning the `[` requires they key-combo of `AltGr+8`?

If so, could you try this:
```diff
       extraKeys: {
+        "Alt-8": this.handleLeftBracket,
         "[": this.handleLeftBracket,
```

Note: I'm not sure if the physical AltGr key will work, so could you try both left and right Alt keys.

It would also be helpful if you could provide the information from [key-event-viewer](https://w3c.github.io/uievents/tools/key-event-viewer.html) of you pressing/generating `[`.

Lastly, did you manage to try https://github.com/alonswartz/notesium/issues/28#issuecomment-1875722303 for `jj` instead of `[[`?

**Comment by Pupo1** [comment] 2024-01-05 05:55
Yes, that is true, AltGr + 8

It is my birthday today, to I will postpone the tests for tomorrow :-)

**Comment by Pupo1** [comment] 2024-01-09 20:24
I did make a few tests, but they were all not successful. 

Very sorry to say, but I stumbled over Obsidian again, which I had
rejected a long time ago, because I could not install it at that time,
now it worked like a charm, and I chose to go with that one. 

The two reasons are the following: 
1- it has all the advantages that notesium has
2- most important: I have to admit that I don't like your naming
concept. When I go into that notes folder, I want to be able to do like
"echo missed the bus again >> 2024-01-09.md", I just don't see sense in
going through hundreds of 6595blah.md - files until I have the right
one. I think that QOrgNotes and also Obsidian do it right, you name as
whatever you want - or you don't, then it will be just unnamed-33.md ,
and whenever you choose to rename your file, the program will just
search for links in other notes and adapt those links.

**Comment by alonswartz** [comment] 2024-01-10 13:05
Obsidian is a good choice! You need to find a tool which works for you.

FWIW, the decision to construct filenames as 8-hexidecimal-digits wasn't adhoc. I won't go into it here as I documented the rationale [here](https://github.com/alonswartz/notesium?tab=readme-ov-file#filenames-are-8-hexidecimal-digits).

That said, I can completely understand your comment about trying to find a specific file, but don't forget Notesium is a CLI tool, for example:

```
$ notesium list --prefix=label | grep books
643bf345.md:1: books how to take smart notes
62695278.md:1: books made to stick
64392a1f.md:1: books never split the difference
...
```

As for a *daily-log*, I'd propose using deterministic filenames, for example:

```
$ cat today.sh
today_s="$(date +"%F 00:00:01")"
today_epoch_int="$(date -d "$today_s" "+%s")"
today_epoch_hex="$(printf '%x' "$today_epoch_int")"
echo ${today_epoch_hex}.md

$ ./today.sh
659dc1e1.md
```

I do something similar to this, but for a *weekly-log*. It's currently a script executed by a keybinding which creates the note if it doesn't exist (with title), and either opens it or switches focus to it if already open. I plan on integrating something similar to this into Notesium itself in the future.

Happy birthday!

**Comment by Pupo1** [comment] 2024-01-10 20:49
Thanks for the explanation! And keep up the good work. 

Best regards, Bernd

**Comment by nextlevelshit** [comment] 2024-10-11 11:30
Could not catch up the whole conversation. I am having the same issues, german layout, `[[` is not working except I change the keyboard layout to any EN.

**Comment by alonswartz** [comment] 2024-10-13 09:58
Hey @nextlevelshit - thanks for bringing up this issue again.
I've setup a test environment and can replicate the issue. I'll work on a fix and get back to you soon as I can.

**Comment by alonswartz** [comment] 2024-10-13 14:23
@nextlevelshit - could you test this and let me know if it works for you?
http://alonswartz-temp.s3-website-us-east-1.amazonaws.com/cmtest-de/

**Comment by nextlevelshit** [comment] 2024-10-13 14:49
like a charme

![image](https://github.com/user-attachments/assets/825f8a12-01e7-466f-a6c5-32cc673941b5)

**Comment by alonswartz** [comment] 2024-10-16 13:11
@nextlevelshit apologies on the delay, I came across a few edge cases which needed to be addressed. I now have two implementations which should work (they also display keydown events for debugging purposes).

- **[baseline](http://alonswartz-temp.s3-website-us-east-1.amazonaws.com/cmtest-de/baseline/)** - this is the baseline status quo for reference.
- **[cm-patch](http://alonswartz-temp.s3-website-us-east-1.amazonaws.com/cmtest-de/cm-patch/)** - an improved version of what you initially tested, except this should also handle indentation keybindings.
- **[keypress](http://alonswartz-temp.s3-website-us-east-1.amazonaws.com/cmtest-de/keypress/)** - should also work for both link insertion and indentation, but does not require patching codemirror.

Do you mind testing again and letting me know what works and what doesn't?

**Comment by nextlevelshit** [comment] 2024-10-21 18:05
Ok, here I am. A bit late to the show, sorry @alonswartz!

baseline:  

![image](https://github.com/user-attachments/assets/f0c6e9d6-f6f0-4b9e-bfad-460e72475ec9)

cm-path:

![image](https://github.com/user-attachments/assets/8e3b2538-db50-48bf-b671-c761c52d1b09)

keypress:

![image](https://github.com/user-attachments/assets/25ff99f4-1371-41fe-8432-00c989b30ff4)

**Comment by alonswartz** [comment] 2024-10-22 12:46
@nextlevelshit excellent, thanks for testing and your patience. I'll release a new version with the fix as soon as I can.

**Comment by alonswartz** [comment] 2024-10-27 10:31
@nextlevelshit - The issue should now be addressed. However, instead of issuing a new release immediately, I'd like to provide you with a build that includes the fix for testing. I'll be updating the GitHub Actions workflow to upload the build artifacts for this purpose and will share the download link here once it's available.

Thanks again for your patience!

**Comment by alonswartz** [comment] 2024-10-27 13:08
@nextlevelshit - I've updated the GitHub Actions to upload the build artifacts.

The latest build is available [here](https://github.com/alonswartz/notesium/actions/runs/11540609565) (scroll down to the **Artifacts** section). The artifact is a ZIP file containing builds for Linux, macOS, and Windows, along with supporting files. Please extract the binary for your OS and let me know if everything works as expected.

**Comment by nextlevelshit** [comment] 2024-10-27 16:19
Looks like it's working!

![image](https://github.com/user-attachments/assets/c63f5c2e-07e8-47da-8391-c9f21f58b350)

**Comment by alonswartz** [comment] 2024-10-30 10:24
Thanks for the confirmation!

BTW - The bracket handling has been changed a little / improved to handle other keyboard layouts (#72) - and per my tests DE should continue to work as expected. Additionally, a new keybinding (`Alt-k`) has been added to trigger the InsertLink dialog.

If you'd like to test it, the build artifacts are available [here](https://github.com/alonswartz/notesium/actions/runs/11590662259).

I'm going to close this issue for now, please re-open if you come across any problems.

**Closed by alonswartz** 2024-10-30 10:24 UTC

**Comment by alonswartz** [comment] 2024-11-07 11:20
This is now part of the [Notesium v0.6.1 release](https://github.com/alonswartz/notesium/releases/tag/v0.6.1). Thanks for your help and patience!

**Comment by nextlevelshit** [comment] 2024-11-15 21:34
Having a fallback with `Alt + k` for triggering the dialog makes much sense. Giving the user multiple ways to do the same thing is not a bad design pattern ;) Thanks for you effort
